export const projects = [
  {
    icon: "/images/social-app.png",
    label: "Social Media App",
    text: "Built an intuitive e-commerce platform with smooth product browsing and secure checkout",
    id: "1",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "Next.js",
      "Typescribt",
      "REST API",
      "Redux Toolkit",
      "React icons",
    ],
    link: "https://social-app-two-red.vercel.app/login",
    repo: "https://github.com/Hadywahba/Social-APP",
  },
  {
    icon: "/images/THINK-UP.png",
    label: "ThinkUp",
    text: "Note-taking app designed for easy creation, organization, and management of notes, featuring a clean interface and smooth user experience",
    id: "2",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "React.js",
      "zod",
      "Javascribt",
      "Redux Toolkit",
      "Context API",
      "React icons",
      "REST API",
      "sweetalert2",
      "react-hook-form",
    ],
    link: "https://note-app-puce-psi.vercel.app/login",
    repo: "https://github.com/Hadywahba/Note-App",
  },
  {
    icon: "/images/Macbook-Air.png",
    label: " Fresh Cart | E-commerce website for products. ",
    text: "Integrated a seamless e-commerce platform for easy browsing and secure purchasing of products. ",
    id: "3",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "React.js",
      "Javascribt",
      "Redux Toolkit",
      "REST API",
      "Context API",
      "FontAwesome",
      "React icons",
      
      
    ],
    link: "https://fresh-cart-red-eight.vercel.app/",
    repo: "https://github.com/Hadywahba/Fresh-Cart",
  },

  {
    icon: "/images/menu.png",
    label: "Yummy",
    text: "Web application for restaurants that allows users to select their favorite recipes and save them to their favorites list.",
    id: "4",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "React.js",
      "FontAwesome",
      "REST API",
      "Javascribt",
    ],
    link: "https://menu-dusky-eight.vercel.app/",
    repo: "https://github.com/Hadywahba/Menu",
  },
  {
    icon: "/images/weather.png",
    label: "weather",
    text: "Weather App is a web application that provides real-time weather information for 3 days in different countries with the ability to search for a specific country, Stay informed about the current temperature, wind speed, humidity, and cloud cover.",
    id: "5",
    tech: ["HTML", "CSS", "Bootstrap","REST API" ,"FontAwesome", "Javascribt"],
    link: "https://hadywahba.github.io/weather/",
    repo: "https://github.com/Hadywahba/weather",
  },
  {
    icon: "/images/bookmark.png",
    label: "Bookmarker",
    text: "Bookmark is a web application that allows users to bookmark their favorite websites, it provides basic CRUD (Create, Read, Update, Delete) operations for managing bookmarks. ",
    id: "6",
    tech: ["HTML", "CSS", "Bootstrap", "Javascribt", "FontAwesome"],
    link: "https://hadywahba.github.io/Bookmark/",
    repo: "https://github.com/Hadywahba/Bookmark",
  },
  {
    icon: "/images/login system.png",
    label: "Login System",
    text: "Login System website is a system for creating an account and logging in through it to reach the welcome page.",

    id: "7",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "React.js",
      "FontAwesome",
      "REST API",
      "Javascribt",
    ],
    link: "https://hadywahba.github.io/login/signin.html",
    repo: "https://github.com/Hadywahba/login",
  },
  {
    icon: "/images/Daniel.png",
    label: "Daniel",
    text: "A ui website is personal project.",

    id: "8",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "React.js",
      "FontAwesome",
      "REST API",
      "Javascribt",
    ],
    link: "https://hadywahba.github.io/Daniels/",
    repo: "https://github.com/Hadywahba/Daniels",
  },
];

console.log(projects);
