export const projects = [
  {
    icon: '/images/manarah.png',
    label: 'Al Manara',
    text: 'Al Manara is a modern corporate website that presents the company’s sectors, services, and vision through a clean, responsive, and multilingual experience.',
    id: '1',
    tech: [
      'HTML',
      'CSS',
      'Next.js',
      'next-intl',
      'TypeScript',
      'Tailwind CSS',
      'React Hook Form',
      'Zod',
      'REST API',
      'shadcn',
      'React Context',
      'React Query',
    ],
    link: 'https://almanarh.com.sa/en',
  },
  {
    icon: '/images/power-fit.png',
    label: 'Power-Fit',
    text: 'Super Fitness is a modern fitness platform designed to help users achieve their health and workout goals through personalized training programs, effective exercises, and a motivating user experience',
    id: '2',
    tech: [
      'HTML',
      'CSS',
      'React.js',
      'next-intl',
      'TypeScript',
      'Tailwind CSS',
      'React Hook Form',
      'Zod',
      'REST API',
      'shadcn',
      'React Context',
      'React Query',
    ],
    link: 'https://power-fit-green.vercel.app/',
  },
  {
    icon: '/images/rose.png',
    label: 'Rose',
    text: 'Rose is an elegant e-commerce platform specialized in flowers, making it easy to browse, select, and send beautiful floral arrangements',
    id: '3',
    tech: [
      'HTML',
      'CSS',
      'Next.js',
      'NextAuth',
      'Google Maps API',
      'next-intl',
      'TypeScript',
      'Tailwind CSS',
      'React Hook Form',
      'Zod',
      'REST API',
      'shadcn',
      'React Context',
      'React Query',
    ],
    link: 'https://rose-lac-iota.vercel.app/en',
    repo: 'https://github.com/Hadywahba/Rose',
  },
  {
    icon: '/images/amer.png',
    label: 'Amer Plus',
    text: 'Amer Plus is an educational platform offering students comprehensive lessons, practice exams, and video tutorials to support learning and academic success.',
    id: '4',
    tech: [
      'HTML',
      'CSS',
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'React Hook Form',
      'Zod',
      'REST API',
      'Zustand',
      'React Query',
    ],
    link: 'https://amer-plus.com/',
  },
  {
    icon: '/images/exam.png',
    label: 'Exam App',
    text: 'A comprehensive exam management system built with Next.js 14, featuring authentication, exam creation, and result tracking.',
    id: '5',
    tech: [
      'HTML',
      'CSS',
      'Next.js',
      'NextAuth',
      'TypeScript',
      'Tailwind CSS',
      'shadcn/ui',
      'React Hook Form',
      'Zod',
      'REST API',
      'React Context',
      'React Query',
    ],
    link: 'https://exam-app-brown.vercel.app/',
    repo: 'https://github.com/Hadywahba/exam-app',
  },
  {
    icon: '/images/post-pilot.png',
    label: 'PostPilot Landing page',
    text: 'A modern, animated landing page built with smooth scroll interactions, Swiper sliders, and Framer Motion animations.',
    id: '6',
    tech: [
      'HTML',
      'CSS',
      'Next.js',
      'TypeScript',
      'Swiper',
      'Framer Motion',
      'React Icons',
    ],
    link: 'https://post-pilot-eta.vercel.app/',
    repo: 'https://github.com/Hadywahba/Post-Pilot',
  },
  // {
  //   icon: '/images/social-app.png',
  //   label: 'Social Media App',
  //   text: 'Built an intuitive e-commerce platform with smooth product browsing and secure checkout',
  //   id: '7',
  //   tech: [
  //     'HTML',
  //     'CSS',
  //     'MUI',
  //     'Next.js',
  //     'TypeScript',
  //     'REST API',
  //     'Redux Toolkit',
  //     'React icons',
  //   ],
  //   link: 'https://social-app-five-delta.vercel.app/login',
  //   repo: 'https://github.com/Hadywahba/Social-APP',
  // },
  {
    icon: '/images/THINK-UP.png',
    label: 'ThinkUp',
    text: 'Note-taking app designed for easy creation, organization, and management of notes, featuring a clean interface and smooth user experience',
    id: '8',
    tech: [
      'HTML',
      'CSS',
      'Tailwind',
      'React.js',
      'zod',
      'JavaScript',
      'Redux Toolkit',
      'React Context',
      'React icons',
      'REST API',
      'sweetAlert2',
      'React Hook Form',
    ],
    link: 'https://note-app-puce-psi.vercel.app/login',
    repo: 'https://github.com/Hadywahba/Note-App',
  },
  {
    icon: '/images/Macbook-Air.png',
    label: ' Fresh Cart | E-commerce website for products. ',
    text: 'Integrated a seamless e-commerce platform for easy browsing and secure purchasing of products. ',
    id: '9',
    tech: [
      'HTML',
      'CSS',
      'Tailwind',
      'React.js',
      'JavaScript',
      'Redux Toolkit',
      'REST API',
      'React Context',
      'FontAwesome',
      'React icons',
    ],
    link: 'https://fresh-cart-red-eight.vercel.app/',
    repo: 'https://github.com/Hadywahba/Fresh-Cart',
  },

  {
    icon: '/images/menu.png',
    label: 'Yummy',
    text: 'Web application for restaurants that allows users to select their favorite recipes and save them to their favorites list.',
    id: '10',
    tech: [
      'HTML',
      'CSS',
      'Tailwind',
      'React.js',
      'FontAwesome',
      'REST API',
      'JavaScript',
    ],
    link: 'https://menu-dusky-eight.vercel.app/',
    repo: 'https://github.com/Hadywahba/Menu',
  },
  {
    icon: '/images/weather.png',
    label: 'weather',
    text: 'Weather App is a web application that provides real-time weather information for 3 days in different countries with the ability to search for a specific country, Stay informed about the current temperature, wind speed, humidity, and cloud cover.',
    id: '11',
    tech: ['HTML', 'CSS', 'Bootstrap', 'REST API', 'FontAwesome', 'JavaScript'],
    link: 'https://hadywahba.github.io/weather/',
    repo: 'https://github.com/Hadywahba/weather',
  },
  {
    icon: '/images/bookmark.png',
    label: 'Bookmarker',
    text: 'Bookmark is a web application that allows users to bookmark their favorite websites, it provides basic CRUD (Create, Read, Update, Delete) operations for managing bookmarks. ',
    id: '12',
    tech: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'FontAwesome'],
    link: 'https://hadywahba.github.io/Bookmark/',
    repo: 'https://github.com/Hadywahba/Bookmark',
  },
  {
    icon: '/images/login system.png',
    label: 'Login System',
    text: 'Login System website is a system for creating an account and logging in through it to reach the welcome page.',

    id: '13',
    tech: [
      'HTML',
      'CSS',
      'Tailwind',
      'React.js',
      'FontAwesome',
      'REST API',
      'JavaScript',
    ],
    link: 'https://hadywahba.github.io/login/signin.html',
    repo: 'https://github.com/Hadywahba/login',
  },
  {
    icon: '/images/Daniel.png',
    label: 'Daniel',
    text: 'A ui website is personal project.',

    id: '14',
    tech: [
      'HTML',
      'CSS',
      'Tailwind',
      'React.js',
      'FontAwesome',
      'REST API',
      'JavaScript',
    ],
    link: 'https://hadywahba.github.io/Daniels/',
    repo: 'https://github.com/Hadywahba/Daniels',
  },
];
